version: '3.3'

services:
  main:
    container_name: frontend-app
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: "npm run dev"
    restart: always
